"""address dict + timezone in stations

Revision ID: 5bd878b62adf
Revises: 7e5768397d3e
Create Date: 2026-04-17 12:11:24.256254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd878b62adf'
down_revision: Union[str, Sequence[str], None] = '7e5768397d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('timezone', sa.String(), nullable=False))
    op.alter_column('stations', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='address::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'address',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('stations', 'timezone')
    # ### end Alembic commands ###
