"""new columns at stations

Revision ID: 7e5768397d3e
Revises: c640980df8ad
Create Date: 2026-04-17 11:47:07.157917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5768397d3e'
down_revision: Union[str, Sequence[str], None] = 'c640980df8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('stations', sa.Column('opening_hours', sa.String(), nullable=False))
    op.add_column('stations', sa.Column('phone_numbers', sa.JSON(), nullable=False))
    op.add_column('stations', sa.Column('websites', sa.JSON(), nullable=False))
    op.drop_column('stations', 'corpo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('corpo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('stations', 'websites')
    op.drop_column('stations', 'phone_numbers')
    op.drop_column('stations', 'opening_hours')
    op.drop_column('stations', 'price')
    # ### end Alembic commands ###
