"""new column bout rating

Revision ID: 7ffd291f8867
Revises: 5bd878b62adf
Create Date: 2026-04-17 12:34:17.314036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffd291f8867'
down_revision: Union[str, Sequence[str], None] = '5bd878b62adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('overall_rate', sa.Integer(), nullable=False))
    op.add_column('stations', sa.Column('people_rated', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'people_rated')
    op.drop_column('stations', 'overall_rate')
    # ### end Alembic commands ###
