"""empty message

Revision ID: c640980df8ad
Revises: 2b1398bf9ebd
Create Date: 2026-04-17 10:59:18.884374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c640980df8ad'
down_revision: Union[str, Sequence[str], None] = '2b1398bf9ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'characteristics',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='characteristics::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'characteristics',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
