"""stations table

Revision ID: d4fa4c355e6e
Revises: c8d5d52080c3
Create Date: 2026-04-12 01:55:57.107540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fa4c355e6e'
down_revision: Union[str, Sequence[str], None] = 'c8d5d52080c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
